services:

  backend:
    build:
      context: ./backend/AdoptaUnCompaneroApplication-3
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/adopta_un_companero?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PracticaRoot
    volumes:
    - ./uploads:/app/uploads
    networks:
      - adopta_net

  frontend:
    build:
      context: ./frontend/proyecto-adopta-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ""
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - adopta_net

networks:
  adopta_net:
    driver: bridge